name: the newspaper ci

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: setting_up
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run:  |
          sudo apt update
          sudo apt upgrade
          sudo apt install -y python3 wkhtmltopdf
          sudo pip install -r requirements.txt
      # Runs a single command using the runners shell
      - name: Run spider script
        run: bash spider.sh

      - name: zipup_the_hindu
        run: zip -r the_hindu.zip /home/runner/newspaper/the_hindu || true

      - name: zipup_business_standard
        run: zip -r business_standard .zip /home/runner/newspaper/business_standard || true

      - name: zipup_financial_express
        run: zip -r financial_express.zip /home/runner/newspaper/financial_express || true

      - name: zipup_livemint
        run: zip -r livemint.zip /home/runner/newspaper/livemint || true

      - name: zipup_economic_times
        run: zip -r economic_times.zip /home/runner/newspaper/economic_times || true

      - name: zipup_indian_express
        run: zip -r indian_express.zip /home/runner/newspaper/indian_express || true

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "/home/runner/work/newspaper/newspaper/*.zip"
          token: ${{ secrets.NP_SECRET_TOKEN }}
